# Generated by Django 2.2.6 on 2021-06-05 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0020_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
