# Generated by Django 2.2.6 on 2021-06-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0025_auto_20210611_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='Подаголовок поста', max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Заголовок поста', max_length=25),
        ),
    ]
