# Generated by Django 2.2.6 on 2021-10-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_auto_20210612_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(default='Подзаголовок поста', max_length=50, verbose_name='подзаголовок'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='Заголовок поста', max_length=25, verbose_name='заголовок'),
        ),
    ]
